### ISSUE TITLE
Nette 2.3.x compatibility

### ISSUE THREAD

**Issue by landsman** [ThunboltCMS/bar#1]
Hi,

i have fw v: 2.3.10 (released on 2016-04-13) where bar return exception:

> Argument 1 passed to Tracy\Bar::addPanel() must implement interface Tracy\IBarPanel, ....

**Comment by MartkCz** [comment]
Hi, can you please try dev version?

I now read full text of exception, how did you register this extension?

Only with this?

``` yaml
extensions:
    bar: Thunbolt\Bar\DI\BarExtension
```

**Comment by MartkCz** [comment]
I now read full text of exception, how did you register this extension?

Only with this?
```yaml
extensions:
    bar: Thunbolt\Bar\DI\BarExtension
```

**Comment by landsman** [comment]
Sure

**Comment by landsman** [comment]
What can I do for testing?
